apiVersion: v1
kind: Service
metadata:
  name: employee-api-svc
  labels:
    app: employee-api
spec:
  type: LoadBalancer
  selector:
    app: employee-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080